name: Build and Push to ECR

on: 
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_FRONTEND_REPO: jerin/wpoms-web
  ECR_BACKEND_REPO: jerin/wpoms-admin

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR (to get ecr uri)
        id: login-ecr 
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Images to ECR
        id: build-images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }} # Uses the commit hash as the unique image tag
        run: |
          # Build the docker container
          docker compose build backend 
          docker compose build frontend 

          # tag the docker images
          docker tag wpoms_admin:latest $ECR_REGISTRY/$ECR_BACKEND_REPO:$IMAGE_TAG
          docker tag wpoms_web:latest $ECR_REGISTRY/$ECR_FRONTEND_REPO:$IMAGE_TAG

          # Also tag it as 'latest' so the EC2 script can always pull the newest version easily
          docker tag wpoms_admin:latest $ECR_REGISTRY/$ECR_BACKEND_REPO:latest
          docker tag wpoms_web:latest $ECR_REGISTRY/$ECR_FRONTEND_REPO:latest
          
          # Push both tags to ECR
          docker push $ECR_REGISTRY/$ECR_BACKEND_REPO:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_FRONTEND_REPO:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_BACKEND_REPO:latest
          docker push $ECR_REGISTRY/$ECR_FRONTEND_REPO:latest
